---
name: Git linter
"on":
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the code
        uses: actions/checkout@v2
        with:
          fetch-depth: '20'
      - name: Lint
        uses: g4s8/gitlint-action@0.3.1
        with:
          since: "2020-05-13"
