---
name: PDD linter
"on":
  push:
    branches:
      - master
  pull_request:
    brranches:
      - master
jobs:
  pdd-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: g4s8/pdd-action@master
